### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by motisobat** [jbkinney/logomaker#9] opened 2020-02-09 19:01 UTC
I got this error while running the code in a jupyter notebook:

AttributeError: module 'logomaker' has no attribute 'Logo'

what can I do?

**Comment by atareen** [comment] 2020-02-09 20:40
Hi can you share/paste the snippet of code you used in your notebook for running logomaker? Also, which version of python are you using?

**Comment by motisobat** [comment] 2020-02-09 20:53
Hi, 
My Python version is 3.5.3
My code is:
`import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 
plt.ion()

import logomaker
mymatrix = pd.read_csv('1.txt', delim_whitespace=True, index_col=0)
mymatrix.head()
logomaker.Logo(-mymatrix, center_values=True)`

The error is:
AttributeError                            Traceback (most recent call last)
<ipython-input-23-7bcae6c5e6d1> in <module>
----> 1 logomaker.Logo(-mymatrix, center_values=True)

AttributeError: module 'logomaker' has no attribute 'Logo'

**Comment by atareen** [comment] 2020-02-09 21:11
Hi again, 

did you pip install logomaker or did you clone the github repo? I just ran the following on my laptop to check expected behavior (i.e. see attached screenshot). Are you able to run logomaker.demo()? Otherwise, after importing logomaker, can you run `dir(logomaker)` and check if your version of logomaker has the Logo class? When you run `import logomaker` does it throw an error? Can you also run `logomaker.__path__` after importing to figure out if there's a duplicate package issue.

If you did use pip, is your pip updated? I recall that older versions of pip (e.g. < 9.0.0) had some issues. If I had to guess, this seems like an installation issue. Let me know about these details, particularly how you installed logomaker. I would be happy to do a test install and demo logomaker's use on google colab to help figure this out.

<img width="1430" alt="Screenshot 2020-02-09 16 01 50" src="https://user-images.githubusercontent.com/6977064/74109895-a7ef4280-4b55-11ea-9897-4ab00be3dfab.png">

**Comment by motisobat** [comment] 2020-02-09 21:51
I pip3 installed logomaker. I updatad my pip, its version is 20.0.2

When I use Jupyter notebook or atom, dir(logomaker) return these:(Does not include Logos)
['Path',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'get_ipython',
 'ipython',
 'lm',
 'np',
 'os',
 'pd',
 'plt']
 
But when I use command line, using IPython, dir(logomaker)  does include Logo class.
I am able to run logomaker.demo() in command line but not in jupyter or atom.

 When you run import logomaker does it throw an error?  No

In terminal:
In [20]: logomaker.__path__                                                     
Out[20]: ['/usr/local/lib/python3.5/dist-packages/logomaker']

in Jupyter:
logomaker.__path__

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-933fad732ae3> in <module>
----> 1 logomaker.__path__

AttributeError: module 'logomaker' has no attribute '__path__'


Also when I want to use Logo attribute in jupyter i got an error:
logomaker.Logo(-mymatrix, center_values=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7bcae6c5e6d1> in <module>
----> 1 logomaker.Logo(-mymatrix, center_values=True)

AttributeError: module 'logomaker' has no attribute 'Logo'


In terminal, it seems that it work with no error but no new window showing my logo pups up!
In [19]: logomaker.Logo(-mymatrix, center_values=True)                          
Out[19]: <logomaker.src.Logo.Logo at 0x7fda588e52b0>

**Comment by atareen** [comment] 2020-02-09 22:42
Okay, this appears to be a path issue with pip on your machine and not with logomaker. I think your pip3 path is set to work with python in your terminal but not with jupyter notebook, which may be using a different python environment. 

For example see: https://github.com/jupyter/notebook/issues/1524

There are many such issues on github/stackoverflow you can find to resolve which version of pip (i.e. pip, pip2.7, pip3 etc.) should point to where, and to figure out which location your jupyter kernel is looking for when you import a package.

A possible solution to this issue for you would be to run the following line directly in your jupyter notebook before before importing logomaker (note the use of !, and possible restart of kernel may be required):

`!pip install logomaker`

<img width="1014" alt="Screenshot 2020-02-09 17 36 15" src="https://user-images.githubusercontent.com/6977064/74111483-c6a80600-4b62-11ea-8996-bc024c79cb73.png">

This should use the pip configured with your jupyter and not the pip that's pointing to your terminal.

I hope this helps. As I said, since logomaker works on your terminal, I am convinced that this is not a logomaker issue and rather an python path issue on your machine. Therefore I am closing the issue. 

p.s. In my jupyter notebook, I run `logomaker.__path__` (with two underscores before and after path) rather than `logomaker.path`, to check the location of the package.

**Closed by atareen** 2020-02-09 22:42 UTC
